#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_PhongTro.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_Phong_Tro")]
	public partial class DataQLPhong_TroDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCT_TrangBi(CT_TrangBi instance);
    partial void UpdateCT_TrangBi(CT_TrangBi instance);
    partial void DeleteCT_TrangBi(CT_TrangBi instance);
    partial void InsertDỊch_vụ(DỊch_vụ instance);
    partial void UpdateDỊch_vụ(DỊch_vụ instance);
    partial void DeleteDỊch_vụ(DỊch_vụ instance);
    partial void InsertHóa_đơn(Hóa_đơn instance);
    partial void UpdateHóa_đơn(Hóa_đơn instance);
    partial void DeleteHóa_đơn(Hóa_đơn instance);
    partial void InsertHOPDONG(HOPDONG instance);
    partial void UpdateHOPDONG(HOPDONG instance);
    partial void DeleteHOPDONG(HOPDONG instance);
    partial void InsertKhách_hàng(Khách_hàng instance);
    partial void UpdateKhách_hàng(Khách_hàng instance);
    partial void DeleteKhách_hàng(Khách_hàng instance);
    partial void InsertLoại_thiết_bị(Loại_thiết_bị instance);
    partial void UpdateLoại_thiết_bị(Loại_thiết_bị instance);
    partial void DeleteLoại_thiết_bị(Loại_thiết_bị instance);
    partial void InsertLoại_phòng(Loại_phòng instance);
    partial void UpdateLoại_phòng(Loại_phòng instance);
    partial void DeleteLoại_phòng(Loại_phòng instance);
    partial void InsertNhân_viên_QL(Nhân_viên_QL instance);
    partial void UpdateNhân_viên_QL(Nhân_viên_QL instance);
    partial void DeleteNhân_viên_QL(Nhân_viên_QL instance);
    partial void InsertPhòng(Phòng instance);
    partial void UpdatePhòng(Phòng instance);
    partial void DeletePhòng(Phòng instance);
    partial void InsertTài_khoản(Tài_khoản instance);
    partial void UpdateTài_khoản(Tài_khoản instance);
    partial void DeleteTài_khoản(Tài_khoản instance);
    partial void InsertThiết_bị(Thiết_bị instance);
    partial void UpdateThiết_bị(Thiết_bị instance);
    partial void DeleteThiết_bị(Thiết_bị instance);
    partial void InsertThống_kê(Thống_kê instance);
    partial void UpdateThống_kê(Thống_kê instance);
    partial void DeleteThống_kê(Thống_kê instance);
    #endregion
		
		public DataQLPhong_TroDataContext() : 
				base(global::QL_PhongTro.Properties.Settings.Default.QL_Phong_TroConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLPhong_TroDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLPhong_TroDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLPhong_TroDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLPhong_TroDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CT_TrangBi> CT_TrangBis
		{
			get
			{
				return this.GetTable<CT_TrangBi>();
			}
		}
		
		public System.Data.Linq.Table<DỊch_vụ> DỊch_vụs
		{
			get
			{
				return this.GetTable<DỊch_vụ>();
			}
		}
		
		public System.Data.Linq.Table<Hóa_đơn> Hóa_đơns
		{
			get
			{
				return this.GetTable<Hóa_đơn>();
			}
		}
		
		public System.Data.Linq.Table<HOPDONG> HOPDONGs
		{
			get
			{
				return this.GetTable<HOPDONG>();
			}
		}
		
		public System.Data.Linq.Table<Khách_hàng> Khách_hàngs
		{
			get
			{
				return this.GetTable<Khách_hàng>();
			}
		}
		
		public System.Data.Linq.Table<Loại_thiết_bị> Loại_thiết_bịs
		{
			get
			{
				return this.GetTable<Loại_thiết_bị>();
			}
		}
		
		public System.Data.Linq.Table<Loại_phòng> Loại_phòngs
		{
			get
			{
				return this.GetTable<Loại_phòng>();
			}
		}
		
		public System.Data.Linq.Table<Nhân_viên_QL> Nhân_viên_QLs
		{
			get
			{
				return this.GetTable<Nhân_viên_QL>();
			}
		}
		
		public System.Data.Linq.Table<Phòng> Phòngs
		{
			get
			{
				return this.GetTable<Phòng>();
			}
		}
		
		public System.Data.Linq.Table<Tài_khoản> Tài_khoảns
		{
			get
			{
				return this.GetTable<Tài_khoản>();
			}
		}
		
		public System.Data.Linq.Table<Thiết_bị> Thiết_bịs
		{
			get
			{
				return this.GetTable<Thiết_bị>();
			}
		}
		
		public System.Data.Linq.Table<Thống_kê> Thống_kês
		{
			get
			{
				return this.GetTable<Thống_kê>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_TrangBi")]
	public partial class CT_TrangBi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mã_phòng;
		
		private string _Ma_thiết_bị;
		
		private System.Nullable<int> _SL_trang_bi;
		
		private System.Nullable<System.DateTime> _Ngay_TB;
		
		private EntityRef<Phòng> _Phòng;
		
		private EntityRef<Thiết_bị> _Thiết_bị;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMã_phòngChanging(string value);
    partial void OnMã_phòngChanged();
    partial void OnMa_thiết_bịChanging(string value);
    partial void OnMa_thiết_bịChanged();
    partial void OnSL_trang_biChanging(System.Nullable<int> value);
    partial void OnSL_trang_biChanged();
    partial void OnNgay_TBChanging(System.Nullable<System.DateTime> value);
    partial void OnNgay_TBChanged();
    #endregion
		
		public CT_TrangBi()
		{
			this._Phòng = default(EntityRef<Phòng>);
			this._Thiết_bị = default(EntityRef<Thiết_bị>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã phòng]", Storage="_Mã_phòng", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mã_phòng
		{
			get
			{
				return this._Mã_phòng;
			}
			set
			{
				if ((this._Mã_phòng != value))
				{
					this.OnMã_phòngChanging(value);
					this.SendPropertyChanging();
					this._Mã_phòng = value;
					this.SendPropertyChanged("Mã_phòng");
					this.OnMã_phòngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ma thiết bị]", Storage="_Ma_thiết_bị", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_thiết_bị
		{
			get
			{
				return this._Ma_thiết_bị;
			}
			set
			{
				if ((this._Ma_thiết_bị != value))
				{
					this.OnMa_thiết_bịChanging(value);
					this.SendPropertyChanging();
					this._Ma_thiết_bị = value;
					this.SendPropertyChanged("Ma_thiết_bị");
					this.OnMa_thiết_bịChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SL trang bi]", Storage="_SL_trang_bi", DbType="Int")]
		public System.Nullable<int> SL_trang_bi
		{
			get
			{
				return this._SL_trang_bi;
			}
			set
			{
				if ((this._SL_trang_bi != value))
				{
					this.OnSL_trang_biChanging(value);
					this.SendPropertyChanging();
					this._SL_trang_bi = value;
					this.SendPropertyChanged("SL_trang_bi");
					this.OnSL_trang_biChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ngay TB]", Storage="_Ngay_TB", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngay_TB
		{
			get
			{
				return this._Ngay_TB;
			}
			set
			{
				if ((this._Ngay_TB != value))
				{
					this.OnNgay_TBChanging(value);
					this.SendPropertyChanging();
					this._Ngay_TB = value;
					this.SendPropertyChanged("Ngay_TB");
					this.OnNgay_TBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phòng_CT_TrangBi", Storage="_Phòng", ThisKey="Mã_phòng", OtherKey="Mã_phòng", IsForeignKey=true)]
		public Phòng Phòng
		{
			get
			{
				return this._Phòng.Entity;
			}
			set
			{
				Phòng previousValue = this._Phòng.Entity;
				if (((previousValue != value) 
							|| (this._Phòng.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phòng.Entity = null;
						previousValue.CT_TrangBis.Remove(this);
					}
					this._Phòng.Entity = value;
					if ((value != null))
					{
						value.CT_TrangBis.Add(this);
						this._Mã_phòng = value.Mã_phòng;
					}
					else
					{
						this._Mã_phòng = default(string);
					}
					this.SendPropertyChanged("Phòng");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thiết_bị_CT_TrangBi", Storage="_Thiết_bị", ThisKey="Ma_thiết_bị", OtherKey="Ma_thiết_bị", IsForeignKey=true)]
		public Thiết_bị Thiết_bị
		{
			get
			{
				return this._Thiết_bị.Entity;
			}
			set
			{
				Thiết_bị previousValue = this._Thiết_bị.Entity;
				if (((previousValue != value) 
							|| (this._Thiết_bị.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thiết_bị.Entity = null;
						previousValue.CT_TrangBis.Remove(this);
					}
					this._Thiết_bị.Entity = value;
					if ((value != null))
					{
						value.CT_TrangBis.Add(this);
						this._Ma_thiết_bị = value.Ma_thiết_bị;
					}
					else
					{
						this._Ma_thiết_bị = default(string);
					}
					this.SendPropertyChanged("Thiết_bị");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[DỊch vụ]")]
	public partial class DỊch_vụ : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mã_DV;
		
		private string _Tên_DV;
		
		private string _DVT;
		
		private decimal _Giá_DV;
		
		private EntitySet<Hóa_đơn> _Hóa_đơns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMã_DVChanging(string value);
    partial void OnMã_DVChanged();
    partial void OnTên_DVChanging(string value);
    partial void OnTên_DVChanged();
    partial void OnDVTChanging(string value);
    partial void OnDVTChanged();
    partial void OnGiá_DVChanging(decimal value);
    partial void OnGiá_DVChanged();
    #endregion
		
		public DỊch_vụ()
		{
			this._Hóa_đơns = new EntitySet<Hóa_đơn>(new Action<Hóa_đơn>(this.attach_Hóa_đơns), new Action<Hóa_đơn>(this.detach_Hóa_đơns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã DV]", Storage="_Mã_DV", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mã_DV
		{
			get
			{
				return this._Mã_DV;
			}
			set
			{
				if ((this._Mã_DV != value))
				{
					this.OnMã_DVChanging(value);
					this.SendPropertyChanging();
					this._Mã_DV = value;
					this.SendPropertyChanged("Mã_DV");
					this.OnMã_DVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tên DV]", Storage="_Tên_DV", DbType="NVarChar(20)")]
		public string Tên_DV
		{
			get
			{
				return this._Tên_DV;
			}
			set
			{
				if ((this._Tên_DV != value))
				{
					this.OnTên_DVChanging(value);
					this.SendPropertyChanging();
					this._Tên_DV = value;
					this.SendPropertyChanged("Tên_DV");
					this.OnTên_DVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVT", DbType="NVarChar(10)")]
		public string DVT
		{
			get
			{
				return this._DVT;
			}
			set
			{
				if ((this._DVT != value))
				{
					this.OnDVTChanging(value);
					this.SendPropertyChanging();
					this._DVT = value;
					this.SendPropertyChanged("DVT");
					this.OnDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Giá DV]", Storage="_Giá_DV", DbType="Money NOT NULL")]
		public decimal Giá_DV
		{
			get
			{
				return this._Giá_DV;
			}
			set
			{
				if ((this._Giá_DV != value))
				{
					this.OnGiá_DVChanging(value);
					this.SendPropertyChanging();
					this._Giá_DV = value;
					this.SendPropertyChanged("Giá_DV");
					this.OnGiá_DVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DỊch_vụ_Hóa_đơn", Storage="_Hóa_đơns", ThisKey="Mã_DV", OtherKey="Mã_DV")]
		public EntitySet<Hóa_đơn> Hóa_đơns
		{
			get
			{
				return this._Hóa_đơns;
			}
			set
			{
				this._Hóa_đơns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Hóa_đơns(Hóa_đơn entity)
		{
			this.SendPropertyChanging();
			entity.DỊch_vụ = this;
		}
		
		private void detach_Hóa_đơns(Hóa_đơn entity)
		{
			this.SendPropertyChanging();
			entity.DỊch_vụ = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Hóa đơn]")]
	public partial class Hóa_đơn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Số_hóa_đơn;
		
		private string _MaNV;
		
		private string _Mã_DV;
		
		private string _SoHD;
		
		private EntityRef<DỊch_vụ> _DỊch_vụ;
		
		private EntityRef<HOPDONG> _HOPDONG;
		
		private EntityRef<Nhân_viên_QL> _Nhân_viên_QL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSố_hóa_đơnChanging(string value);
    partial void OnSố_hóa_đơnChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnMã_DVChanging(string value);
    partial void OnMã_DVChanged();
    partial void OnSoHDChanging(string value);
    partial void OnSoHDChanged();
    #endregion
		
		public Hóa_đơn()
		{
			this._DỊch_vụ = default(EntityRef<DỊch_vụ>);
			this._HOPDONG = default(EntityRef<HOPDONG>);
			this._Nhân_viên_QL = default(EntityRef<Nhân_viên_QL>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Số hóa đơn]", Storage="_Số_hóa_đơn", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Số_hóa_đơn
		{
			get
			{
				return this._Số_hóa_đơn;
			}
			set
			{
				if ((this._Số_hóa_đơn != value))
				{
					this.OnSố_hóa_đơnChanging(value);
					this.SendPropertyChanging();
					this._Số_hóa_đơn = value;
					this.SendPropertyChanged("Số_hóa_đơn");
					this.OnSố_hóa_đơnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._Nhân_viên_QL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã DV]", Storage="_Mã_DV", DbType="Char(5)")]
		public string Mã_DV
		{
			get
			{
				return this._Mã_DV;
			}
			set
			{
				if ((this._Mã_DV != value))
				{
					this.OnMã_DVChanging(value);
					this.SendPropertyChanging();
					this._Mã_DV = value;
					this.SendPropertyChanged("Mã_DV");
					this.OnMã_DVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHD", DbType="Char(5)")]
		public string SoHD
		{
			get
			{
				return this._SoHD;
			}
			set
			{
				if ((this._SoHD != value))
				{
					if (this._HOPDONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSoHDChanging(value);
					this.SendPropertyChanging();
					this._SoHD = value;
					this.SendPropertyChanged("SoHD");
					this.OnSoHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DỊch_vụ_Hóa_đơn", Storage="_DỊch_vụ", ThisKey="Mã_DV", OtherKey="Mã_DV", IsForeignKey=true)]
		public DỊch_vụ DỊch_vụ
		{
			get
			{
				return this._DỊch_vụ.Entity;
			}
			set
			{
				DỊch_vụ previousValue = this._DỊch_vụ.Entity;
				if (((previousValue != value) 
							|| (this._DỊch_vụ.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DỊch_vụ.Entity = null;
						previousValue.Hóa_đơns.Remove(this);
					}
					this._DỊch_vụ.Entity = value;
					if ((value != null))
					{
						value.Hóa_đơns.Add(this);
						this._Mã_DV = value.Mã_DV;
					}
					else
					{
						this._Mã_DV = default(string);
					}
					this.SendPropertyChanged("DỊch_vụ");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOPDONG_Hóa_đơn", Storage="_HOPDONG", ThisKey="SoHD", OtherKey="SoHD", IsForeignKey=true)]
		public HOPDONG HOPDONG
		{
			get
			{
				return this._HOPDONG.Entity;
			}
			set
			{
				HOPDONG previousValue = this._HOPDONG.Entity;
				if (((previousValue != value) 
							|| (this._HOPDONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOPDONG.Entity = null;
						previousValue.Hóa_đơns.Remove(this);
					}
					this._HOPDONG.Entity = value;
					if ((value != null))
					{
						value.Hóa_đơns.Add(this);
						this._SoHD = value.SoHD;
					}
					else
					{
						this._SoHD = default(string);
					}
					this.SendPropertyChanged("HOPDONG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhân_viên_QL_Hóa_đơn", Storage="_Nhân_viên_QL", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public Nhân_viên_QL Nhân_viên_QL
		{
			get
			{
				return this._Nhân_viên_QL.Entity;
			}
			set
			{
				Nhân_viên_QL previousValue = this._Nhân_viên_QL.Entity;
				if (((previousValue != value) 
							|| (this._Nhân_viên_QL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nhân_viên_QL.Entity = null;
						previousValue.Hóa_đơns.Remove(this);
					}
					this._Nhân_viên_QL.Entity = value;
					if ((value != null))
					{
						value.Hóa_đơns.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("Nhân_viên_QL");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOPDONG")]
	public partial class HOPDONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SoHD;
		
		private System.Nullable<System.DateTime> _NgayLapHD;
		
		private System.Nullable<System.DateTime> _ThoiHanHD;
		
		private string _Mã_KH;
		
		private string _Mã_phòng;
		
		private string _MaNV;
		
		private EntitySet<Hóa_đơn> _Hóa_đơns;
		
		private EntityRef<Khách_hàng> _Khách_hàng;
		
		private EntityRef<Nhân_viên_QL> _Nhân_viên_QL;
		
		private EntityRef<Phòng> _Phòng;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoHDChanging(string value);
    partial void OnSoHDChanged();
    partial void OnNgayLapHDChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapHDChanged();
    partial void OnThoiHanHDChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiHanHDChanged();
    partial void OnMã_KHChanging(string value);
    partial void OnMã_KHChanged();
    partial void OnMã_phòngChanging(string value);
    partial void OnMã_phòngChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    #endregion
		
		public HOPDONG()
		{
			this._Hóa_đơns = new EntitySet<Hóa_đơn>(new Action<Hóa_đơn>(this.attach_Hóa_đơns), new Action<Hóa_đơn>(this.detach_Hóa_đơns));
			this._Khách_hàng = default(EntityRef<Khách_hàng>);
			this._Nhân_viên_QL = default(EntityRef<Nhân_viên_QL>);
			this._Phòng = default(EntityRef<Phòng>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHD", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SoHD
		{
			get
			{
				return this._SoHD;
			}
			set
			{
				if ((this._SoHD != value))
				{
					this.OnSoHDChanging(value);
					this.SendPropertyChanging();
					this._SoHD = value;
					this.SendPropertyChanged("SoHD");
					this.OnSoHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLapHD", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayLapHD
		{
			get
			{
				return this._NgayLapHD;
			}
			set
			{
				if ((this._NgayLapHD != value))
				{
					this.OnNgayLapHDChanging(value);
					this.SendPropertyChanging();
					this._NgayLapHD = value;
					this.SendPropertyChanged("NgayLapHD");
					this.OnNgayLapHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiHanHD", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiHanHD
		{
			get
			{
				return this._ThoiHanHD;
			}
			set
			{
				if ((this._ThoiHanHD != value))
				{
					this.OnThoiHanHDChanging(value);
					this.SendPropertyChanging();
					this._ThoiHanHD = value;
					this.SendPropertyChanged("ThoiHanHD");
					this.OnThoiHanHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã KH]", Storage="_Mã_KH", DbType="Char(5)")]
		public string Mã_KH
		{
			get
			{
				return this._Mã_KH;
			}
			set
			{
				if ((this._Mã_KH != value))
				{
					this.OnMã_KHChanging(value);
					this.SendPropertyChanging();
					this._Mã_KH = value;
					this.SendPropertyChanged("Mã_KH");
					this.OnMã_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã phòng]", Storage="_Mã_phòng", DbType="Char(5)")]
		public string Mã_phòng
		{
			get
			{
				return this._Mã_phòng;
			}
			set
			{
				if ((this._Mã_phòng != value))
				{
					this.OnMã_phòngChanging(value);
					this.SendPropertyChanging();
					this._Mã_phòng = value;
					this.SendPropertyChanged("Mã_phòng");
					this.OnMã_phòngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Char(5)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._Nhân_viên_QL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOPDONG_Hóa_đơn", Storage="_Hóa_đơns", ThisKey="SoHD", OtherKey="SoHD")]
		public EntitySet<Hóa_đơn> Hóa_đơns
		{
			get
			{
				return this._Hóa_đơns;
			}
			set
			{
				this._Hóa_đơns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khách_hàng_HOPDONG", Storage="_Khách_hàng", ThisKey="Mã_KH", OtherKey="Mã_KH", IsForeignKey=true)]
		public Khách_hàng Khách_hàng
		{
			get
			{
				return this._Khách_hàng.Entity;
			}
			set
			{
				Khách_hàng previousValue = this._Khách_hàng.Entity;
				if (((previousValue != value) 
							|| (this._Khách_hàng.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khách_hàng.Entity = null;
						previousValue.HOPDONGs.Remove(this);
					}
					this._Khách_hàng.Entity = value;
					if ((value != null))
					{
						value.HOPDONGs.Add(this);
						this._Mã_KH = value.Mã_KH;
					}
					else
					{
						this._Mã_KH = default(string);
					}
					this.SendPropertyChanged("Khách_hàng");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhân_viên_QL_HOPDONG", Storage="_Nhân_viên_QL", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public Nhân_viên_QL Nhân_viên_QL
		{
			get
			{
				return this._Nhân_viên_QL.Entity;
			}
			set
			{
				Nhân_viên_QL previousValue = this._Nhân_viên_QL.Entity;
				if (((previousValue != value) 
							|| (this._Nhân_viên_QL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nhân_viên_QL.Entity = null;
						previousValue.HOPDONGs.Remove(this);
					}
					this._Nhân_viên_QL.Entity = value;
					if ((value != null))
					{
						value.HOPDONGs.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("Nhân_viên_QL");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phòng_HOPDONG", Storage="_Phòng", ThisKey="Mã_phòng", OtherKey="Mã_phòng", IsForeignKey=true)]
		public Phòng Phòng
		{
			get
			{
				return this._Phòng.Entity;
			}
			set
			{
				Phòng previousValue = this._Phòng.Entity;
				if (((previousValue != value) 
							|| (this._Phòng.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phòng.Entity = null;
						previousValue.HOPDONGs.Remove(this);
					}
					this._Phòng.Entity = value;
					if ((value != null))
					{
						value.HOPDONGs.Add(this);
						this._Mã_phòng = value.Mã_phòng;
					}
					else
					{
						this._Mã_phòng = default(string);
					}
					this.SendPropertyChanged("Phòng");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Hóa_đơns(Hóa_đơn entity)
		{
			this.SendPropertyChanging();
			entity.HOPDONG = this;
		}
		
		private void detach_Hóa_đơns(Hóa_đơn entity)
		{
			this.SendPropertyChanging();
			entity.HOPDONG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Khách hàng]")]
	public partial class Khách_hàng : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mã_KH;
		
		private string _Tên_KH;
		
		private System.Nullable<System.DateTime> _Năm_sinh;
		
		private string _Sđt;
		
		private string _CMND;
		
		private string _Quê_quán;
		
		private EntitySet<HOPDONG> _HOPDONGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMã_KHChanging(string value);
    partial void OnMã_KHChanged();
    partial void OnTên_KHChanging(string value);
    partial void OnTên_KHChanged();
    partial void OnNăm_sinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNăm_sinhChanged();
    partial void OnSđtChanging(string value);
    partial void OnSđtChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnQuê_quánChanging(string value);
    partial void OnQuê_quánChanged();
    #endregion
		
		public Khách_hàng()
		{
			this._HOPDONGs = new EntitySet<HOPDONG>(new Action<HOPDONG>(this.attach_HOPDONGs), new Action<HOPDONG>(this.detach_HOPDONGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã KH]", Storage="_Mã_KH", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mã_KH
		{
			get
			{
				return this._Mã_KH;
			}
			set
			{
				if ((this._Mã_KH != value))
				{
					this.OnMã_KHChanging(value);
					this.SendPropertyChanging();
					this._Mã_KH = value;
					this.SendPropertyChanged("Mã_KH");
					this.OnMã_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tên KH]", Storage="_Tên_KH", DbType="NVarChar(20)")]
		public string Tên_KH
		{
			get
			{
				return this._Tên_KH;
			}
			set
			{
				if ((this._Tên_KH != value))
				{
					this.OnTên_KHChanging(value);
					this.SendPropertyChanging();
					this._Tên_KH = value;
					this.SendPropertyChanged("Tên_KH");
					this.OnTên_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Năm sinh]", Storage="_Năm_sinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> Năm_sinh
		{
			get
			{
				return this._Năm_sinh;
			}
			set
			{
				if ((this._Năm_sinh != value))
				{
					this.OnNăm_sinhChanging(value);
					this.SendPropertyChanging();
					this._Năm_sinh = value;
					this.SendPropertyChanged("Năm_sinh");
					this.OnNăm_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sđt", DbType="Char(10)")]
		public string Sđt
		{
			get
			{
				return this._Sđt;
			}
			set
			{
				if ((this._Sđt != value))
				{
					this.OnSđtChanging(value);
					this.SendPropertyChanging();
					this._Sđt = value;
					this.SendPropertyChanged("Sđt");
					this.OnSđtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Char(9)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Quê quán]", Storage="_Quê_quán", DbType="NVarChar(50)")]
		public string Quê_quán
		{
			get
			{
				return this._Quê_quán;
			}
			set
			{
				if ((this._Quê_quán != value))
				{
					this.OnQuê_quánChanging(value);
					this.SendPropertyChanging();
					this._Quê_quán = value;
					this.SendPropertyChanged("Quê_quán");
					this.OnQuê_quánChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khách_hàng_HOPDONG", Storage="_HOPDONGs", ThisKey="Mã_KH", OtherKey="Mã_KH")]
		public EntitySet<HOPDONG> HOPDONGs
		{
			get
			{
				return this._HOPDONGs;
			}
			set
			{
				this._HOPDONGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOPDONGs(HOPDONG entity)
		{
			this.SendPropertyChanging();
			entity.Khách_hàng = this;
		}
		
		private void detach_HOPDONGs(HOPDONG entity)
		{
			this.SendPropertyChanging();
			entity.Khách_hàng = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Loại thiết bị]")]
	public partial class Loại_thiết_bị : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mã_loại_TB;
		
		private EntitySet<Thiết_bị> _Thiết_bịs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMã_loại_TBChanging(string value);
    partial void OnMã_loại_TBChanged();
    #endregion
		
		public Loại_thiết_bị()
		{
			this._Thiết_bịs = new EntitySet<Thiết_bị>(new Action<Thiết_bị>(this.attach_Thiết_bịs), new Action<Thiết_bị>(this.detach_Thiết_bịs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã loại TB]", Storage="_Mã_loại_TB", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mã_loại_TB
		{
			get
			{
				return this._Mã_loại_TB;
			}
			set
			{
				if ((this._Mã_loại_TB != value))
				{
					this.OnMã_loại_TBChanging(value);
					this.SendPropertyChanging();
					this._Mã_loại_TB = value;
					this.SendPropertyChanged("Mã_loại_TB");
					this.OnMã_loại_TBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Loại_thiết_bị_Thiết_bị", Storage="_Thiết_bịs", ThisKey="Mã_loại_TB", OtherKey="Mã_loại_TB")]
		public EntitySet<Thiết_bị> Thiết_bịs
		{
			get
			{
				return this._Thiết_bịs;
			}
			set
			{
				this._Thiết_bịs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Thiết_bịs(Thiết_bị entity)
		{
			this.SendPropertyChanging();
			entity.Loại_thiết_bị = this;
		}
		
		private void detach_Thiết_bịs(Thiết_bị entity)
		{
			this.SendPropertyChanging();
			entity.Loại_thiết_bị = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Loại phòng]")]
	public partial class Loại_phòng : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mã_loại_phòng;
		
		private string _TenLP;
		
		private EntitySet<Phòng> _Phòngs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMã_loại_phòngChanging(string value);
    partial void OnMã_loại_phòngChanged();
    partial void OnTenLPChanging(string value);
    partial void OnTenLPChanged();
    #endregion
		
		public Loại_phòng()
		{
			this._Phòngs = new EntitySet<Phòng>(new Action<Phòng>(this.attach_Phòngs), new Action<Phòng>(this.detach_Phòngs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã loại phòng]", Storage="_Mã_loại_phòng", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mã_loại_phòng
		{
			get
			{
				return this._Mã_loại_phòng;
			}
			set
			{
				if ((this._Mã_loại_phòng != value))
				{
					this.OnMã_loại_phòngChanging(value);
					this.SendPropertyChanging();
					this._Mã_loại_phòng = value;
					this.SendPropertyChanged("Mã_loại_phòng");
					this.OnMã_loại_phòngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLP", DbType="NVarChar(20)")]
		public string TenLP
		{
			get
			{
				return this._TenLP;
			}
			set
			{
				if ((this._TenLP != value))
				{
					this.OnTenLPChanging(value);
					this.SendPropertyChanging();
					this._TenLP = value;
					this.SendPropertyChanged("TenLP");
					this.OnTenLPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Loại_phòng_Phòng", Storage="_Phòngs", ThisKey="Mã_loại_phòng", OtherKey="Mã_loại_phòng")]
		public EntitySet<Phòng> Phòngs
		{
			get
			{
				return this._Phòngs;
			}
			set
			{
				this._Phòngs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Phòngs(Phòng entity)
		{
			this.SendPropertyChanging();
			entity.Loại_phòng = this;
		}
		
		private void detach_Phòngs(Phòng entity)
		{
			this.SendPropertyChanging();
			entity.Loại_phòng = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Nhân viên QL]")]
	public partial class Nhân_viên_QL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _Tên_NV;
		
		private EntitySet<Hóa_đơn> _Hóa_đơns;
		
		private EntitySet<HOPDONG> _HOPDONGs;
		
		private EntitySet<Tài_khoản> _Tài_khoảns;
		
		private EntitySet<Thống_kê> _Thống_kês;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTên_NVChanging(string value);
    partial void OnTên_NVChanged();
    #endregion
		
		public Nhân_viên_QL()
		{
			this._Hóa_đơns = new EntitySet<Hóa_đơn>(new Action<Hóa_đơn>(this.attach_Hóa_đơns), new Action<Hóa_đơn>(this.detach_Hóa_đơns));
			this._HOPDONGs = new EntitySet<HOPDONG>(new Action<HOPDONG>(this.attach_HOPDONGs), new Action<HOPDONG>(this.detach_HOPDONGs));
			this._Tài_khoảns = new EntitySet<Tài_khoản>(new Action<Tài_khoản>(this.attach_Tài_khoảns), new Action<Tài_khoản>(this.detach_Tài_khoảns));
			this._Thống_kês = new EntitySet<Thống_kê>(new Action<Thống_kê>(this.attach_Thống_kês), new Action<Thống_kê>(this.detach_Thống_kês));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tên NV]", Storage="_Tên_NV", DbType="NVarChar(20)")]
		public string Tên_NV
		{
			get
			{
				return this._Tên_NV;
			}
			set
			{
				if ((this._Tên_NV != value))
				{
					this.OnTên_NVChanging(value);
					this.SendPropertyChanging();
					this._Tên_NV = value;
					this.SendPropertyChanged("Tên_NV");
					this.OnTên_NVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhân_viên_QL_Hóa_đơn", Storage="_Hóa_đơns", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<Hóa_đơn> Hóa_đơns
		{
			get
			{
				return this._Hóa_đơns;
			}
			set
			{
				this._Hóa_đơns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhân_viên_QL_HOPDONG", Storage="_HOPDONGs", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<HOPDONG> HOPDONGs
		{
			get
			{
				return this._HOPDONGs;
			}
			set
			{
				this._HOPDONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhân_viên_QL_Tài_khoản", Storage="_Tài_khoảns", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<Tài_khoản> Tài_khoảns
		{
			get
			{
				return this._Tài_khoảns;
			}
			set
			{
				this._Tài_khoảns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhân_viên_QL_Thống_kê", Storage="_Thống_kês", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<Thống_kê> Thống_kês
		{
			get
			{
				return this._Thống_kês;
			}
			set
			{
				this._Thống_kês.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Hóa_đơns(Hóa_đơn entity)
		{
			this.SendPropertyChanging();
			entity.Nhân_viên_QL = this;
		}
		
		private void detach_Hóa_đơns(Hóa_đơn entity)
		{
			this.SendPropertyChanging();
			entity.Nhân_viên_QL = null;
		}
		
		private void attach_HOPDONGs(HOPDONG entity)
		{
			this.SendPropertyChanging();
			entity.Nhân_viên_QL = this;
		}
		
		private void detach_HOPDONGs(HOPDONG entity)
		{
			this.SendPropertyChanging();
			entity.Nhân_viên_QL = null;
		}
		
		private void attach_Tài_khoảns(Tài_khoản entity)
		{
			this.SendPropertyChanging();
			entity.Nhân_viên_QL = this;
		}
		
		private void detach_Tài_khoảns(Tài_khoản entity)
		{
			this.SendPropertyChanging();
			entity.Nhân_viên_QL = null;
		}
		
		private void attach_Thống_kês(Thống_kê entity)
		{
			this.SendPropertyChanging();
			entity.Nhân_viên_QL = this;
		}
		
		private void detach_Thống_kês(Thống_kê entity)
		{
			this.SendPropertyChanging();
			entity.Nhân_viên_QL = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phòng")]
	public partial class Phòng : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mã_phòng;
		
		private string _Mã_loại_phòng;
		
		private int _SucChua;
		
		private int _DTSD;
		
		private string _Huong;
		
		private EntitySet<CT_TrangBi> _CT_TrangBis;
		
		private EntitySet<HOPDONG> _HOPDONGs;
		
		private EntityRef<Loại_phòng> _Loại_phòng;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMã_phòngChanging(string value);
    partial void OnMã_phòngChanged();
    partial void OnMã_loại_phòngChanging(string value);
    partial void OnMã_loại_phòngChanged();
    partial void OnSucChuaChanging(int value);
    partial void OnSucChuaChanged();
    partial void OnDTSDChanging(int value);
    partial void OnDTSDChanged();
    partial void OnHuongChanging(string value);
    partial void OnHuongChanged();
    #endregion
		
		public Phòng()
		{
			this._CT_TrangBis = new EntitySet<CT_TrangBi>(new Action<CT_TrangBi>(this.attach_CT_TrangBis), new Action<CT_TrangBi>(this.detach_CT_TrangBis));
			this._HOPDONGs = new EntitySet<HOPDONG>(new Action<HOPDONG>(this.attach_HOPDONGs), new Action<HOPDONG>(this.detach_HOPDONGs));
			this._Loại_phòng = default(EntityRef<Loại_phòng>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã phòng]", Storage="_Mã_phòng", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mã_phòng
		{
			get
			{
				return this._Mã_phòng;
			}
			set
			{
				if ((this._Mã_phòng != value))
				{
					this.OnMã_phòngChanging(value);
					this.SendPropertyChanging();
					this._Mã_phòng = value;
					this.SendPropertyChanged("Mã_phòng");
					this.OnMã_phòngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã loại phòng]", Storage="_Mã_loại_phòng", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string Mã_loại_phòng
		{
			get
			{
				return this._Mã_loại_phòng;
			}
			set
			{
				if ((this._Mã_loại_phòng != value))
				{
					this.OnMã_loại_phòngChanging(value);
					this.SendPropertyChanging();
					this._Mã_loại_phòng = value;
					this.SendPropertyChanged("Mã_loại_phòng");
					this.OnMã_loại_phòngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SucChua", DbType="Int NOT NULL")]
		public int SucChua
		{
			get
			{
				return this._SucChua;
			}
			set
			{
				if ((this._SucChua != value))
				{
					this.OnSucChuaChanging(value);
					this.SendPropertyChanging();
					this._SucChua = value;
					this.SendPropertyChanged("SucChua");
					this.OnSucChuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DTSD", DbType="Int NOT NULL")]
		public int DTSD
		{
			get
			{
				return this._DTSD;
			}
			set
			{
				if ((this._DTSD != value))
				{
					this.OnDTSDChanging(value);
					this.SendPropertyChanging();
					this._DTSD = value;
					this.SendPropertyChanged("DTSD");
					this.OnDTSDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Huong", DbType="Char(4)")]
		public string Huong
		{
			get
			{
				return this._Huong;
			}
			set
			{
				if ((this._Huong != value))
				{
					this.OnHuongChanging(value);
					this.SendPropertyChanging();
					this._Huong = value;
					this.SendPropertyChanged("Huong");
					this.OnHuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phòng_CT_TrangBi", Storage="_CT_TrangBis", ThisKey="Mã_phòng", OtherKey="Mã_phòng")]
		public EntitySet<CT_TrangBi> CT_TrangBis
		{
			get
			{
				return this._CT_TrangBis;
			}
			set
			{
				this._CT_TrangBis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phòng_HOPDONG", Storage="_HOPDONGs", ThisKey="Mã_phòng", OtherKey="Mã_phòng")]
		public EntitySet<HOPDONG> HOPDONGs
		{
			get
			{
				return this._HOPDONGs;
			}
			set
			{
				this._HOPDONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Loại_phòng_Phòng", Storage="_Loại_phòng", ThisKey="Mã_loại_phòng", OtherKey="Mã_loại_phòng", IsForeignKey=true)]
		public Loại_phòng Loại_phòng
		{
			get
			{
				return this._Loại_phòng.Entity;
			}
			set
			{
				Loại_phòng previousValue = this._Loại_phòng.Entity;
				if (((previousValue != value) 
							|| (this._Loại_phòng.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Loại_phòng.Entity = null;
						previousValue.Phòngs.Remove(this);
					}
					this._Loại_phòng.Entity = value;
					if ((value != null))
					{
						value.Phòngs.Add(this);
						this._Mã_loại_phòng = value.Mã_loại_phòng;
					}
					else
					{
						this._Mã_loại_phòng = default(string);
					}
					this.SendPropertyChanged("Loại_phòng");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_TrangBis(CT_TrangBi entity)
		{
			this.SendPropertyChanging();
			entity.Phòng = this;
		}
		
		private void detach_CT_TrangBis(CT_TrangBi entity)
		{
			this.SendPropertyChanging();
			entity.Phòng = null;
		}
		
		private void attach_HOPDONGs(HOPDONG entity)
		{
			this.SendPropertyChanging();
			entity.Phòng = this;
		}
		
		private void detach_HOPDONGs(HOPDONG entity)
		{
			this.SendPropertyChanging();
			entity.Phòng = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Tài khoản]")]
	public partial class Tài_khoản : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTK;
		
		private string _User_name;
		
		private string _Password;
		
		private string _MaNV;
		
		private EntityRef<Nhân_viên_QL> _Nhân_viên_QL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTKChanging(string value);
    partial void OnMaTKChanged();
    partial void OnUser_nameChanging(string value);
    partial void OnUser_nameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    #endregion
		
		public Tài_khoản()
		{
			this._Nhân_viên_QL = default(EntityRef<Nhân_viên_QL>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTK", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTK
		{
			get
			{
				return this._MaTK;
			}
			set
			{
				if ((this._MaTK != value))
				{
					this.OnMaTKChanging(value);
					this.SendPropertyChanging();
					this._MaTK = value;
					this.SendPropertyChanged("MaTK");
					this.OnMaTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[User name]", Storage="_User_name", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string User_name
		{
			get
			{
				return this._User_name;
			}
			set
			{
				if ((this._User_name != value))
				{
					this.OnUser_nameChanging(value);
					this.SendPropertyChanging();
					this._User_name = value;
					this.SendPropertyChanged("User_name");
					this.OnUser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Char(5)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._Nhân_viên_QL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhân_viên_QL_Tài_khoản", Storage="_Nhân_viên_QL", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public Nhân_viên_QL Nhân_viên_QL
		{
			get
			{
				return this._Nhân_viên_QL.Entity;
			}
			set
			{
				Nhân_viên_QL previousValue = this._Nhân_viên_QL.Entity;
				if (((previousValue != value) 
							|| (this._Nhân_viên_QL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nhân_viên_QL.Entity = null;
						previousValue.Tài_khoảns.Remove(this);
					}
					this._Nhân_viên_QL.Entity = value;
					if ((value != null))
					{
						value.Tài_khoảns.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("Nhân_viên_QL");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Thiết bị]")]
	public partial class Thiết_bị : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_thiết_bị;
		
		private string _TenTB;
		
		private string _Mã_loại_TB;
		
		private EntitySet<CT_TrangBi> _CT_TrangBis;
		
		private EntityRef<Loại_thiết_bị> _Loại_thiết_bị;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_thiết_bịChanging(string value);
    partial void OnMa_thiết_bịChanged();
    partial void OnTenTBChanging(string value);
    partial void OnTenTBChanged();
    partial void OnMã_loại_TBChanging(string value);
    partial void OnMã_loại_TBChanged();
    #endregion
		
		public Thiết_bị()
		{
			this._CT_TrangBis = new EntitySet<CT_TrangBi>(new Action<CT_TrangBi>(this.attach_CT_TrangBis), new Action<CT_TrangBi>(this.detach_CT_TrangBis));
			this._Loại_thiết_bị = default(EntityRef<Loại_thiết_bị>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ma thiết bị]", Storage="_Ma_thiết_bị", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_thiết_bị
		{
			get
			{
				return this._Ma_thiết_bị;
			}
			set
			{
				if ((this._Ma_thiết_bị != value))
				{
					this.OnMa_thiết_bịChanging(value);
					this.SendPropertyChanging();
					this._Ma_thiết_bị = value;
					this.SendPropertyChanged("Ma_thiết_bị");
					this.OnMa_thiết_bịChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTB", DbType="NVarChar(30)")]
		public string TenTB
		{
			get
			{
				return this._TenTB;
			}
			set
			{
				if ((this._TenTB != value))
				{
					this.OnTenTBChanging(value);
					this.SendPropertyChanging();
					this._TenTB = value;
					this.SendPropertyChanged("TenTB");
					this.OnTenTBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã loại TB]", Storage="_Mã_loại_TB", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string Mã_loại_TB
		{
			get
			{
				return this._Mã_loại_TB;
			}
			set
			{
				if ((this._Mã_loại_TB != value))
				{
					this.OnMã_loại_TBChanging(value);
					this.SendPropertyChanging();
					this._Mã_loại_TB = value;
					this.SendPropertyChanged("Mã_loại_TB");
					this.OnMã_loại_TBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thiết_bị_CT_TrangBi", Storage="_CT_TrangBis", ThisKey="Ma_thiết_bị", OtherKey="Ma_thiết_bị")]
		public EntitySet<CT_TrangBi> CT_TrangBis
		{
			get
			{
				return this._CT_TrangBis;
			}
			set
			{
				this._CT_TrangBis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Loại_thiết_bị_Thiết_bị", Storage="_Loại_thiết_bị", ThisKey="Mã_loại_TB", OtherKey="Mã_loại_TB", IsForeignKey=true)]
		public Loại_thiết_bị Loại_thiết_bị
		{
			get
			{
				return this._Loại_thiết_bị.Entity;
			}
			set
			{
				Loại_thiết_bị previousValue = this._Loại_thiết_bị.Entity;
				if (((previousValue != value) 
							|| (this._Loại_thiết_bị.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Loại_thiết_bị.Entity = null;
						previousValue.Thiết_bịs.Remove(this);
					}
					this._Loại_thiết_bị.Entity = value;
					if ((value != null))
					{
						value.Thiết_bịs.Add(this);
						this._Mã_loại_TB = value.Mã_loại_TB;
					}
					else
					{
						this._Mã_loại_TB = default(string);
					}
					this.SendPropertyChanged("Loại_thiết_bị");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_TrangBis(CT_TrangBi entity)
		{
			this.SendPropertyChanging();
			entity.Thiết_bị = this;
		}
		
		private void detach_CT_TrangBis(CT_TrangBi entity)
		{
			this.SendPropertyChanging();
			entity.Thiết_bị = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Thống kê]")]
	public partial class Thống_kê : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Số_phiếu_TK;
		
		private string _MaNV;
		
		private EntityRef<Nhân_viên_QL> _Nhân_viên_QL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSố_phiếu_TKChanging(string value);
    partial void OnSố_phiếu_TKChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    #endregion
		
		public Thống_kê()
		{
			this._Nhân_viên_QL = default(EntityRef<Nhân_viên_QL>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Số phiếu TK]", Storage="_Số_phiếu_TK", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Số_phiếu_TK
		{
			get
			{
				return this._Số_phiếu_TK;
			}
			set
			{
				if ((this._Số_phiếu_TK != value))
				{
					this.OnSố_phiếu_TKChanging(value);
					this.SendPropertyChanging();
					this._Số_phiếu_TK = value;
					this.SendPropertyChanged("Số_phiếu_TK");
					this.OnSố_phiếu_TKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._Nhân_viên_QL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhân_viên_QL_Thống_kê", Storage="_Nhân_viên_QL", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public Nhân_viên_QL Nhân_viên_QL
		{
			get
			{
				return this._Nhân_viên_QL.Entity;
			}
			set
			{
				Nhân_viên_QL previousValue = this._Nhân_viên_QL.Entity;
				if (((previousValue != value) 
							|| (this._Nhân_viên_QL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nhân_viên_QL.Entity = null;
						previousValue.Thống_kês.Remove(this);
					}
					this._Nhân_viên_QL.Entity = value;
					if ((value != null))
					{
						value.Thống_kês.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("Nhân_viên_QL");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
